// engine_nnue.cpp
// ================
// RoboGambit 6x6 minimax engine with full NNUE evaluation.
// Built on top of engine.cpp (identical move-gen, search, TT, etc.)
// New additions:
//   - Phase 2: BoardState::accumulator[256], UndoInfo::acc_before[256]
//   - Phase 3: get_feature_index() translation layer
//   - Phase 4: Incremental accumulator updates in init_board_from_array /
//              make_move / unmake_move
//   - Phase 5: nnue_evaluate() replaces evaluate()
//   - Phase 6: GCC unroll pragmas for SIMD-friendly inner loops

#include <iostream>
#include <vector>
#include <string>
#include <cstdint>
#include <unordered_map>
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstring>
#include <random>

// ──────────────────────────────────────────────────────────────────────────────
// NNUE weight tables (auto-generated by export_nnue_weights.py)
// ──────────────────────────────────────────────────────────────────────────────
#include "nnue_weights_v2_5.h"

// RoboGambit 6x6 Constants
constexpr int BOARD_SIZE = 6;
constexpr uint64_t UNIVERSE = 0x0000000FFFFFFFFFULL; // 36 bits

enum Piece
{
    EMPTY = 0,
    W_PAWN = 1,
    W_KNIGHT = 2,
    W_BISHOP = 3,
    W_QUEEN = 4,
    W_KING = 5,
    B_PAWN = 6,
    B_KNIGHT = 7,
    B_BISHOP = 8,
    B_QUEEN = 9,
    B_KING = 10
};

inline bool is_white(int p) { return p >= W_PAWN && p <= W_KING; }
inline bool is_black(int p) { return p >= B_PAWN && p <= B_KING; }
inline bool same_side(int p1, int p2)
{
    if (p1 == EMPTY || p2 == EMPTY)
        return false;
    return (is_white(p1) && is_white(p2)) || (is_black(p1) && is_black(p2));
}

inline int sq_index(int r, int c) { return r * BOARD_SIZE + c; }
inline int sq_row(int idx) { return idx / BOARD_SIZE; }
inline int sq_col(int idx) { return idx % BOARD_SIZE; }
inline bool in_bounds(int r, int c)
{
    return r >= 0 && r < BOARD_SIZE && c >= 0 && c < BOARD_SIZE;
}

// Piece values (for move ordering / SEE only – evaluation is NNUE)
constexpr int PIECE_VALUES[11] = {
    0,
    100, 300, 320, 900, 20000,
    -100, -300, -320, -900, -20000};

constexpr int INITIAL_COUNTS[11] = {
    0,
    6, 2, 2, 1, 1,
    6, 2, 2, 1, 1};

const int ORTHO_DIRS[4][2] = {{-1, 0}, {1, 0}, {0, -1}, {0, 1}};
const int DIAG_DIRS[4][2] = {{-1, -1}, {-1, 1}, {1, -1}, {1, 1}};
const int KNIGHT_DIRS[8][2] = {{-2, -1}, {-2, 1}, {-1, -2}, {-1, 2}, {1, -2}, {1, 2}, {2, -1}, {2, 1}};

// Zobrist
uint64_t ZOBRIST_TABLE[11][36];
uint64_t ZOBRIST_BLACK_TO_MOVE = 0;
uint64_t ZOBRIST_GRAVEYARD[11][4];

std::mt19937_64 rng_zob(42);
inline uint64_t rand64() { return rng_zob(); }

void init_zobrist()
{
    static bool init = false;
    if (init) return;
    init = true;
    for (int p = 0; p <= 10; ++p)
        for (int s = 0; s < 36; ++s)
            ZOBRIST_TABLE[p][s] = rand64();
    ZOBRIST_BLACK_TO_MOVE = rand64();
    for (int p : {W_QUEEN, W_BISHOP, W_KNIGHT, B_QUEEN, B_BISHOP, B_KNIGHT})
    {
        int maxc = INITIAL_COUNTS[p];
        for (int c = 1; c <= maxc; ++c)
            ZOBRIST_GRAVEYARD[p][c] = rand64();
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Phase 2: BoardState with NNUE accumulator
// ──────────────────────────────────────────────────────────────────────────────

struct BoardState
{
    uint64_t bitboards[11] = {0};
    uint64_t white_occupancy = 0;
    uint64_t black_occupancy = 0;
    uint64_t all_occupancy = 0;

    int squares[36] = {0};
    int graveyard[11] = {0};

    bool white_to_move = true;
    uint64_t hash = 0;

    // NNUE dual accumulators
    //   [0] = White's perspective: absolute coords, original piece ids
    //   [1] = Black's perspective: rows flipped (5-r), piece colors swapped
    //         mirrors the canonical_form used during Python training
    int16_t accumulator[2][256];
};

// Transposition Table
struct TTEntry
{
    uint64_t hash = 0;
    int depth = -1;
    int score = 0;
    int flag = 0;
    uint32_t best_move = 0;
};

const int TT_SIZE = 8000000;
TTEntry *TT = new TTEntry[TT_SIZE];

enum TTFlag { TT_EXACT = 0, TT_LOWER = 1, TT_UPPER = 2 };
constexpr int MATE_VALUE = 99999;

uint32_t KILLER_MOVES[64][2];
int HISTORY_TABLE[11][6][6];

std::unordered_map<uint64_t, int> GAME_HISTORY;

struct SearchStats
{
    uint64_t nodes = 0;
    uint64_t cutoffs = 0;
    uint64_t nmp_cutoffs = 0;
    uint64_t lmr_reductions = 0;
    uint64_t lmr_researches = 0;
} STATS;

constexpr int LMR_MIN_MOVE_INDEX = 4;
constexpr int LMR_MIN_DEPTH = 3;
constexpr int NMP_MIN_DEPTH = 4;
constexpr int NMP_BASE_R = 2;
constexpr bool NMP_ADAPTIVE = true;
constexpr int NMP_MARGIN = 60;
constexpr int NMP_MINOR_THRESHOLD = 320;

// Move encoding
inline uint32_t encode_move(int from, int to, int piece, int promo)
{
    return (from & 63) | ((to & 63) << 6) | ((piece & 15) << 12) | ((promo & 15) << 16);
}
inline int move_from(uint32_t m)  { return m & 63; }
inline int move_to(uint32_t m)    { return (m >> 6) & 63; }
inline int move_piece(uint32_t m) { return (m >> 12) & 15; }
inline int move_promo(uint32_t m) { return (m >> 16) & 15; }

inline int store_mate_score(int s, int ply)
{
    if (s > 90000)  return s + ply;
    if (s < -90000) return s - ply;
    return s;
}
inline int retrieve_mate_score(int s, int ply)
{
    if (s > 90000)  return s - ply;
    if (s < -90000) return s + ply;
    return s;
}

inline void hash_piece(BoardState &st, int sq, int piece) { st.hash ^= ZOBRIST_TABLE[piece][sq]; }
inline void hash_side(BoardState &st) { st.hash ^= ZOBRIST_BLACK_TO_MOVE; }
inline void hash_grave(BoardState &st, int piece, int count_before, int count_after)
{
    if (count_before > 0) st.hash ^= ZOBRIST_GRAVEYARD[piece][count_before];
    if (count_after > 0)  st.hash ^= ZOBRIST_GRAVEYARD[piece][count_after];
}

// ──────────────────────────────────────────────────────────────────────────────
// Phase 3: Dual feature index mapping
//
// WHITE perspective (accumulator[0]) – absolute coords, original piece ids:
//   idx = (r * 6 + c) * 10 + (piece - 1)
//
// BLACK perspective (accumulator[1]) – canonical form matching training:
//   Flip rows:   rf = 5 - r
//   Swap colors: White pieces (1-5) → 6-10, Black pieces (6-10) → 1-5
//   idx = (rf * 6 + c) * 10 + (flipped_piece - 1)
// ──────────────────────────────────────────────────────────────────────────────

inline int get_feature_white(int r, int c, int piece)
{
    // White's absolute view – identical to the original single-accumulator formula
    if (piece == EMPTY) return -1;
    return (r * 6 + c) * 10 + (piece - 1);
}

inline int get_feature_black(int r, int c, int piece)
{
    // Black's canonical view: board flipped, own pieces always appear as 1-5
    if (piece == EMPTY) return -1;
    int rf = 5 - r;
    int pc = is_white(piece) ? (piece + 5) : (piece - 5); // swap colors
    return (rf * 6 + c) * 10 + (pc - 1);
}

// ──────────────────────────────────────────────────────────────────────────────
// Phase 4a: Accumulator helpers
// ──────────────────────────────────────────────────────────────────────────────

// Low-level: add/subtract one weight row from one accumulator
inline void acc_add(int16_t acc[256], int feature_idx)
{
    const int16_t *row = &nnue::fc1_weights[feature_idx * 256];
    #pragma GCC unroll 8
    for (int i = 0; i < 256; ++i)
        acc[i] += row[i];
}
inline void acc_sub(int16_t acc[256], int feature_idx)
{
    const int16_t *row = &nnue::fc1_weights[feature_idx * 256];
    #pragma GCC unroll 8
    for (int i = 0; i < 256; ++i)
        acc[i] -= row[i];
}

// High-level: update BOTH perspectives at once
inline void acc_add_piece(BoardState &st, int r, int c, int piece)
{
    acc_add(st.accumulator[0], get_feature_white(r, c, piece));
    acc_add(st.accumulator[1], get_feature_black(r, c, piece));
}
inline void acc_sub_piece(BoardState &st, int r, int c, int piece)
{
    acc_sub(st.accumulator[0], get_feature_white(r, c, piece));
    acc_sub(st.accumulator[1], get_feature_black(r, c, piece));
}

// ──────────────────────────────────────────────────────────────────────────────
// Phase 4b: init_board_from_array – builds accumulator from scratch
// ──────────────────────────────────────────────────────────────────────────────

void init_board_from_array(BoardState &st, int *flat_board, bool playing_white)
{
    init_zobrist();
    st.white_occupancy = st.black_occupancy = st.all_occupancy = 0;
    std::memset(st.bitboards, 0, sizeof(st.bitboards));
    std::memset(st.squares, 0, sizeof(st.squares));
    std::memset(st.graveyard, 0, sizeof(st.graveyard));
    st.hash = 0;

    // Initialise BOTH accumulators to fc1_bias
    for (int i = 0; i < 256; ++i)
        st.accumulator[0][i] = st.accumulator[1][i] = nnue::fc1_bias[i];

    int counts[11] = {0};
    for (int sq = 0; sq < 36; ++sq)
    {
        int p = flat_board[sq];
        st.squares[sq] = p;
        if (p != EMPTY)
        {
            st.bitboards[p] |= (uint64_t(1) << sq);
            if (is_white(p))
                st.white_occupancy |= (uint64_t(1) << sq);
            else
                st.black_occupancy |= (uint64_t(1) << sq);
            counts[p]++;
            hash_piece(st, sq, p);

            // Update both accumulators (White absolute + Black canonical)
            acc_add_piece(st, sq_row(sq), sq_col(sq), p);
        }
    }
    st.all_occupancy = st.white_occupancy | st.black_occupancy;
    st.white_to_move = playing_white;
    if (!playing_white)
        hash_side(st);

    for (int p = 0; p <= 10; ++p)
    {
        if (INITIAL_COUNTS[p] > 0)
        {
            int miss = INITIAL_COUNTS[p] - counts[p];
            if (miss > 0)
            {
                st.graveyard[p] = miss;
                if (p == W_QUEEN || p == W_BISHOP || p == W_KNIGHT ||
                    p == B_QUEEN || p == B_BISHOP || p == B_KNIGHT)
                    hash_grave(st, p, 0, miss);
            }
        }
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Attack / check detection (unchanged from engine.cpp)
// ──────────────────────────────────────────────────────────────────────────────

bool is_attacked(const BoardState &st, int kr, int kc, bool by_white)
{
    const int *b = st.squares;
    auto at = [&](int r, int c) -> int
    {
        if (!in_bounds(r, c)) return EMPTY;
        return b[sq_index(r, c)];
    };

    for (auto &d : ORTHO_DIRS)
    {
        int r = kr + d[0], c = kc + d[1];
        while (in_bounds(r, c))
        {
            int p = at(r, c);
            if (p != EMPTY)
            {
                if (by_white && p == W_QUEEN) return true;
                if (!by_white && p == B_QUEEN) return true;
                break;
            }
            r += d[0]; c += d[1];
        }
    }
    for (auto &d : DIAG_DIRS)
    {
        int r = kr + d[0], c = kc + d[1];
        while (in_bounds(r, c))
        {
            int p = at(r, c);
            if (p != EMPTY)
            {
                if (by_white && (p == W_BISHOP || p == W_QUEEN)) return true;
                if (!by_white && (p == B_BISHOP || p == B_QUEEN)) return true;
                break;
            }
            r += d[0]; c += d[1];
        }
    }
    for (auto &d : KNIGHT_DIRS)
    {
        int r = kr + d[0], c = kc + d[1];
        if (!in_bounds(r, c)) continue;
        int p = at(r, c);
        if (by_white && p == W_KNIGHT) return true;
        if (!by_white && p == B_KNIGHT) return true;
    }
    int pawn_dr = by_white ? -1 : 1;
    for (int dc : {-1, 1})
    {
        int r = kr + pawn_dr, c = kc + dc;
        if (!in_bounds(r, c)) continue;
        int p = at(r, c);
        if (by_white && p == W_PAWN) return true;
        if (!by_white && p == B_PAWN) return true;
    }
    for (int dr = -1; dr <= 1; ++dr)
        for (int dc = -1; dc <= 1; ++dc)
        {
            if (dr == 0 && dc == 0) continue;
            int r = kr + dr, c = kc + dc;
            if (!in_bounds(r, c)) continue;
            int p = at(r, c);
            if (by_white && p == W_KING) return true;
            if (!by_white && p == B_KING) return true;
        }
    return false;
}

bool is_in_check(const BoardState &st, bool checking_white)
{
    int king_piece = checking_white ? W_KING : B_KING;
    for (int sq = 0; sq < 36; ++sq)
        if (st.squares[sq] == king_piece)
            return is_attacked(st, sq_row(sq), sq_col(sq), !checking_white);
    return false;
}

// ──────────────────────────────────────────────────────────────────────────────
// Move generation (unchanged from engine.cpp)
// ──────────────────────────────────────────────────────────────────────────────

void get_pawn_moves(const BoardState &st, int r, int c, int piece, std::vector<uint32_t> &out)
{
    bool is_w = is_white(piece);
    int direction = is_w ? 1 : -1;
    int promotion_rank = is_w ? 5 : 0;
    auto at = [&](int rr, int cc) -> int
    {
        if (!in_bounds(rr, cc)) return EMPTY;
        return st.squares[sq_index(rr, cc)];
    };
    auto add_move = [&](int nr, int nc)
    {
        int dest_sq = sq_index(nr, nc);
        if (nr == promotion_rank)
        {
            if (is_w)
            {
                if (st.graveyard[W_QUEEN]  > 0) out.push_back(encode_move(sq_index(r, c), dest_sq, piece, W_QUEEN));
                if (st.graveyard[W_BISHOP] > 0) out.push_back(encode_move(sq_index(r, c), dest_sq, piece, W_BISHOP));
                if (st.graveyard[W_KNIGHT] > 0) out.push_back(encode_move(sq_index(r, c), dest_sq, piece, W_KNIGHT));
            }
            else
            {
                if (st.graveyard[B_QUEEN]  > 0) out.push_back(encode_move(sq_index(r, c), dest_sq, piece, B_QUEEN));
                if (st.graveyard[B_BISHOP] > 0) out.push_back(encode_move(sq_index(r, c), dest_sq, piece, B_BISHOP));
                if (st.graveyard[B_KNIGHT] > 0) out.push_back(encode_move(sq_index(r, c), dest_sq, piece, B_KNIGHT));
            }
        }
        else
        {
            out.push_back(encode_move(sq_index(r, c), dest_sq, piece, 0));
        }
    };

    int nr = r + direction;
    if (in_bounds(nr, c) && at(nr, c) == EMPTY)
        add_move(nr, c);
    for (int dc : {-1, 1})
    {
        int nc = c + dc;
        if (in_bounds(nr, nc))
        {
            int target = at(nr, nc);
            if (target != EMPTY && !same_side(piece, target))
                add_move(nr, nc);
        }
    }
}

void get_knight_moves(const BoardState &st, int r, int c, int piece, std::vector<uint32_t> &out)
{
    auto at = [&](int rr, int cc) -> int
    {
        if (!in_bounds(rr, cc)) return EMPTY;
        return st.squares[sq_index(rr, cc)];
    };
    for (auto &d : KNIGHT_DIRS)
    {
        int nr = r + d[0], nc = c + d[1];
        if (!in_bounds(nr, nc)) continue;
        int target = at(nr, nc);
        if (target == EMPTY || !same_side(piece, target))
            out.push_back(encode_move(sq_index(r, c), sq_index(nr, nc), piece, 0));
    }
}

void get_sliding_moves(const BoardState &st, int r, int c, int piece,
                       const int dirs[][2], int dir_count,
                       std::vector<uint32_t> &out)
{
    auto at = [&](int rr, int cc) -> int
    {
        if (!in_bounds(rr, cc)) return EMPTY;
        return st.squares[sq_index(rr, cc)];
    };
    int from_sq = sq_index(r, c);
    for (int i = 0; i < dir_count; ++i)
    {
        int dr = dirs[i][0], dc = dirs[i][1];
        int nr = r + dr, nc = c + dc;
        while (in_bounds(nr, nc))
        {
            int target = at(nr, nc);
            int to_sq = sq_index(nr, nc);
            if (target == EMPTY)
            {
                out.push_back(encode_move(from_sq, to_sq, piece, 0));
            }
            else
            {
                if (!same_side(piece, target))
                    out.push_back(encode_move(from_sq, to_sq, piece, 0));
                break;
            }
            nr += dr; nc += dc;
        }
    }
}

void get_king_moves(const BoardState &st, int r, int c, int piece, std::vector<uint32_t> &out)
{
    auto at = [&](int rr, int cc) -> int
    {
        if (!in_bounds(rr, cc)) return EMPTY;
        return st.squares[sq_index(rr, cc)];
    };
    int from_sq = sq_index(r, c);
    for (int dr = -1; dr <= 1; ++dr)
        for (int dc = -1; dc <= 1; ++dc)
        {
            if (dr == 0 && dc == 0) continue;
            int nr = r + dr, nc = c + dc;
            if (!in_bounds(nr, nc)) continue;
            int target = at(nr, nc);
            if (target == EMPTY || !same_side(piece, target))
                out.push_back(encode_move(from_sq, sq_index(nr, nc), piece, 0));
        }
}

void generate_pseudo_moves(const BoardState &st, bool playing_white, std::vector<uint32_t> &out)
{
    out.clear();
    for (int r = 0; r < BOARD_SIZE; ++r)
        for (int c = 0; c < BOARD_SIZE; ++c)
        {
            int sq = sq_index(r, c);
            int piece = st.squares[sq];
            if (piece == EMPTY) continue;
            if (is_white(piece) != playing_white) continue;
            switch (piece)
            {
            case W_PAWN: case B_PAWN:   get_pawn_moves(st, r, c, piece, out); break;
            case W_KNIGHT: case B_KNIGHT: get_knight_moves(st, r, c, piece, out); break;
            case W_BISHOP: case B_BISHOP: get_sliding_moves(st, r, c, piece, DIAG_DIRS, 4, out); break;
            case W_QUEEN: case B_QUEEN:
                get_sliding_moves(st, r, c, piece, DIAG_DIRS, 4, out);
                get_sliding_moves(st, r, c, piece, ORTHO_DIRS, 4, out);
                break;
            case W_KING: case B_KING:   get_king_moves(st, r, c, piece, out); break;
            default: break;
            }
        }
}

void generate_legal_moves(BoardState &st, bool playing_white, std::vector<uint32_t> &out)
{
    std::vector<uint32_t> pseudo;
    generate_pseudo_moves(st, playing_white, pseudo);
    out.clear();

    int our_king = playing_white ? W_KING : B_KING;
    int king_r = -1, king_c = -1;
    for (int sq = 0; sq < 36; ++sq)
        if (st.squares[sq] == our_king) { king_r = sq_row(sq); king_c = sq_col(sq); break; }
    if (king_r == -1) { out.clear(); return; }

    for (uint32_t m : pseudo)
    {
        int from = move_from(m), to = move_to(m);
        int piece = move_piece(m), promo = move_promo(m);
        int captured = st.squares[to];

        hash_piece(st, from, piece);
        if (captured != EMPTY) hash_piece(st, to, captured);

        st.squares[from] = EMPTY;
        st.squares[to] = promo ? promo : piece;

        if (captured != EMPTY)
        {
            st.bitboards[captured] &= ~(uint64_t(1) << to);
            if (is_white(captured)) st.white_occupancy &= ~(uint64_t(1) << to);
            else                    st.black_occupancy &= ~(uint64_t(1) << to);
            st.all_occupancy &= ~(uint64_t(1) << to);
        }
        st.bitboards[piece] &= ~(uint64_t(1) << from);
        st.bitboards[promo ? promo : piece] |= (uint64_t(1) << to);
        if (is_white(piece)) { st.white_occupancy &= ~(uint64_t(1) << from); st.white_occupancy |= (uint64_t(1) << to); }
        else                 { st.black_occupancy &= ~(uint64_t(1) << from); st.black_occupancy |= (uint64_t(1) << to); }
        st.all_occupancy = st.white_occupancy | st.black_occupancy;

        int kr = (piece == our_king) ? sq_row(to) : king_r;
        int kc = (piece == our_king) ? sq_col(to) : king_c;
        bool king_in_check = is_attacked(st, kr, kc, !playing_white);

        st.squares[from] = piece;
        st.squares[to]   = captured;
        st.bitboards[piece] |= (uint64_t(1) << from);
        st.bitboards[promo ? promo : piece] &= ~(uint64_t(1) << to);
        if (captured != EMPTY) st.bitboards[captured] |= (uint64_t(1) << to);
        if (is_white(piece)) { st.white_occupancy &= ~(uint64_t(1) << to); st.white_occupancy |= (uint64_t(1) << from); }
        else                 { st.black_occupancy &= ~(uint64_t(1) << to); st.black_occupancy |= (uint64_t(1) << from); }
        if (captured != EMPTY) {
            if (is_white(captured)) st.white_occupancy |= (uint64_t(1) << to);
            else                    st.black_occupancy |= (uint64_t(1) << to);
        }
        st.all_occupancy = st.white_occupancy | st.black_occupancy;

        hash_piece(st, from, piece);
        if (captured != EMPTY) hash_piece(st, to, captured);

        if (!king_in_check) out.push_back(m);
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Phase 4c: Make / Unmake with accumulator updates
// ──────────────────────────────────────────────────────────────────────────────

struct UndoInfo
{
    int captured_piece;
    int from_sq;
    int to_sq;
    int piece;
    int promo;
    int grave_before[11];
    uint64_t hash_before;
    bool white_to_move_before;
    // Both accumulators saved before the move (2 × 256 × 2 bytes = 1 KB)
    int16_t acc_before[2][256];
};

void make_move(BoardState &st, uint32_t m, UndoInfo &ui)
{
    ui.from_sq = move_from(m);
    ui.to_sq   = move_to(m);
    ui.piece   = move_piece(m);
    ui.promo   = move_promo(m);
    ui.captured_piece = st.squares[ui.to_sq];
    ui.hash_before = st.hash;
    ui.white_to_move_before = st.white_to_move;
    std::memcpy(ui.grave_before, st.graveyard, sizeof(st.graveyard));

    // Save both accumulators (2 × 256 int16 = 1 KB total)
    std::memcpy(ui.acc_before, st.accumulator, sizeof(st.accumulator));

    int from     = ui.from_sq;
    int to       = ui.to_sq;
    int piece    = ui.piece;
    int promo    = ui.promo;
    int captured = ui.captured_piece;

    hash_side(st);
    st.white_to_move = !st.white_to_move;

    hash_piece(st, from, piece);
    if (captured != EMPTY) hash_piece(st, to, captured);

    st.squares[from] = EMPTY;
    st.squares[to]   = promo ? promo : piece;

    // ── Dual accumulator incremental update ──────────────────────────────────
    int arriving_piece = promo ? promo : piece;
    // 1. Remove moving piece from source (both perspectives)
    acc_sub_piece(st, sq_row(from), sq_col(from), piece);
    // 2. Add arriving piece at destination (both perspectives)
    acc_add_piece(st, sq_row(to), sq_col(to), arriving_piece);
    // 3. Remove captured piece (both perspectives)
    if (captured != EMPTY)
        acc_sub_piece(st, sq_row(to), sq_col(to), captured);
    // ── End accumulator update ────────────────────────────────────────────────

    // Bitboards / occupancy
    st.bitboards[piece] &= ~(uint64_t(1) << from);
    if (promo) st.bitboards[promo]  |= (uint64_t(1) << to);
    else       st.bitboards[piece]  |= (uint64_t(1) << to);

    if (is_white(piece))
    {
        st.white_occupancy &= ~(uint64_t(1) << from);
        st.white_occupancy |=  (uint64_t(1) << to);
    }
    else
    {
        st.black_occupancy &= ~(uint64_t(1) << from);
        st.black_occupancy |=  (uint64_t(1) << to);
    }
    if (captured != EMPTY)
    {
        st.bitboards[captured] &= ~(uint64_t(1) << to);
        if (is_white(captured)) st.white_occupancy &= ~(uint64_t(1) << to);
        else                    st.black_occupancy &= ~(uint64_t(1) << to);
    }
    st.all_occupancy = st.white_occupancy | st.black_occupancy;

    // Graveyard
    if (captured != EMPTY &&
        (captured == W_QUEEN || captured == W_BISHOP || captured == W_KNIGHT ||
         captured == B_QUEEN || captured == B_BISHOP || captured == B_KNIGHT))
    {
        int before = st.graveyard[captured];
        int after  = before + 1;
        st.graveyard[captured] = after;
        hash_grave(st, captured, before, after);
    }
    if (promo &&
        (promo == W_QUEEN || promo == W_BISHOP || promo == W_KNIGHT ||
         promo == B_QUEEN || promo == B_BISHOP || promo == B_KNIGHT))
    {
        int before = st.graveyard[promo];
        int after  = std::max(0, before - 1);
        st.graveyard[promo] = after;
        hash_grave(st, promo, before, after);
    }
}

void unmake_move(BoardState &st, const UndoInfo &ui)
{
    int from     = ui.from_sq;
    int to       = ui.to_sq;
    int piece    = ui.piece;
    int promo    = ui.promo;
    int captured = ui.captured_piece;
    int arriving = promo ? promo : piece;

    // Restore scalar state
    st.hash = ui.hash_before;
    st.white_to_move = ui.white_to_move_before;
    std::memcpy(st.graveyard, ui.grave_before, sizeof(st.graveyard));

    // Restore both accumulators (1 KB memcpy – always faster than re-diffing)
    std::memcpy(st.accumulator, ui.acc_before, sizeof(st.accumulator));

    // Restore square map
    st.squares[from] = piece;
    st.squares[to]   = captured;

    // ── XOR-based bitboard restoration (no loop, no memset) ──────────────────
    uint64_t from_bb = uint64_t(1) << from;
    uint64_t to_bb   = uint64_t(1) << to;

    // Remove arriving piece from `to`, restore original piece at `from`
    st.bitboards[arriving] ^= to_bb;
    st.bitboards[piece]    ^= from_bb;

    // Occupancy: moving side toggles both squares
    if (is_white(piece)) { st.white_occupancy ^= (from_bb | to_bb); }
    else                 { st.black_occupancy ^= (from_bb | to_bb); }

    // Restore captured piece at `to`
    if (captured != EMPTY)
    {
        st.bitboards[captured] ^= to_bb;
        if (is_white(captured)) st.white_occupancy ^= to_bb;
        else                    st.black_occupancy ^= to_bb;
    }

    st.all_occupancy = st.white_occupancy | st.black_occupancy;
}

// ──────────────────────────────────────────────────────────────────────────────
// Phase 5: NNUE evaluate()
//
// Forward pass after the accumulator (which holds the S1-scaled fc1 output):
//   1. ReLU the accumulator → activated[256]  (int16_t)
//   2. fc2 dot product      → fc2_out[32]     (int32_t)
//   3. ReLU                 → fc2_act[32]     (int32_t)
//   4. fc3 dot product      → raw_logit       (int32_t)
//
// Output scaling (no sigmoid!):
//   raw_logit represents (cp / 400) * S1 * S2 * S2
//   → centipawns = raw_logit * 400 / (S1 * S2 * S2)
//
// The result is always from White's absolute perspective;
// negate when it is Black's turn so minimax works correctly.
// ──────────────────────────────────────────────────────────────────────────────

int evaluate(const BoardState &st)
{
    // Select accumulator perspective:
    //   [0] = White's absolute view   (queried when White to move)
    //   [1] = Black's canonical view  (queried when Black to move)
    // The model was trained with canonical_form, so its output always represents
    // the CURRENT PLAYER's advantage. We negate for Black to give minimax the
    // White-absolute score it expects.
    const int16_t *acc = st.accumulator[st.white_to_move ? 0 : 1];

    // ── Layer 1 ReLU ─────────────────────────────────────────────────────────
    int16_t activated[256];
    #pragma GCC unroll 8
    for (int i = 0; i < 256; ++i)
        activated[i] = (acc[i] > 0) ? acc[i] : (int16_t)0;

    // ── Layer 2: fc2 ─────────────────────────────────────────────────────────
    int32_t fc2_out[32];
    for (int j = 0; j < 32; ++j)
        fc2_out[j] = nnue::fc2_bias[j];

    for (int i = 0; i < 256; ++i)
    {
        if (activated[i] == 0) continue;   // skip zero rows for speed
        const int16_t *col = &nnue::fc2_weights[i * 32];
        #pragma GCC unroll 8
        for (int j = 0; j < 32; ++j)
            fc2_out[j] += (int32_t)activated[i] * (int32_t)col[j];
    }

    // ── Layer 2 ReLU ─────────────────────────────────────────────────────────
    #pragma GCC unroll 8
    for (int j = 0; j < 32; ++j)
        if (fc2_out[j] < 0) fc2_out[j] = 0;

    // ── Layer 3: fc3 (scalar output) ─────────────────────────────────────────
    int64_t raw_logit = (int64_t)nnue::fc3_bias;
    #pragma GCC unroll 8
    for (int j = 0; j < 32; ++j)
        raw_logit += (int64_t)fc2_out[j] * (int64_t)nnue::fc3_weights[j];

    // raw_logit ≈ (cp / 400) * S1 * S2 * S2   (see nnue_weights.h header)
    constexpr int64_t DENOM = (int64_t)nnue::SCALE_S1 * nnue::SCALE_S2 * nnue::SCALE_S2;
    int cp = (int)(raw_logit * 400LL / DENOM);

    // Model output = "current player advantage"
    // → negate for Black so minimax always sees White-absolute centipawns
    return st.white_to_move ? cp : -cp;
}

// ──────────────────────────────────────────────────────────────────────────────
// NMP helpers and SEE (unchanged logic from engine.cpp)
// ──────────────────────────────────────────────────────────────────────────────

int nmp_reduction(int depth)
{
    if (!NMP_ADAPTIVE) return NMP_BASE_R;
    return (depth <= 4) ? 2 : 3;
}

bool nmp_is_safe(const BoardState &st, bool playing_white, int alpha, int beta)
{
    if (is_in_check(st, playing_white)) return false;
    int wm = 0, bm = 0;
    for (int sq = 0; sq < 36; ++sq)
    {
        int p = st.squares[sq];
        if (p == W_KNIGHT || p == W_BISHOP || p == W_QUEEN) wm += std::abs(PIECE_VALUES[p]);
        else if (p == B_KNIGHT || p == B_BISHOP || p == B_QUEEN) bm += std::abs(PIECE_VALUES[p]);
    }
    if (wm < NMP_MINOR_THRESHOLD && bm < NMP_MINOR_THRESHOLD) return false;
    int stat = evaluate(st);
    if (playing_white) return stat >= beta + NMP_MARGIN;
    return stat <= alpha - NMP_MARGIN;
}

int static_exchange_evaluation(const BoardState &st, int sr, int sc, int dr, int dc)
{
    int dest_sq = sq_index(dr, dc);
    int piece_captured = st.squares[dest_sq];
    if (piece_captured == EMPTY) return 0;
    int piece_moved = st.squares[sq_index(sr, sc)];
    bool is_w = is_white(piece_moved);

    int enemies = 0, allies = -1;
    auto tally = [&](int p) { if (is_white(p) == is_w) allies++; else enemies++; };
    auto at = [&](int r, int c) -> int
    {
        if (!in_bounds(r, c)) return EMPTY;
        return st.squares[sq_index(r, c)];
    };

    for (auto &d : ORTHO_DIRS)
    {
        int r = dr + d[0], c = dc + d[1];
        while (in_bounds(r, c))
        {
            int p = at(r, c);
            if (p != EMPTY) { if (p == W_QUEEN || p == B_QUEEN) tally(p); break; }
            r += d[0]; c += d[1];
        }
    }
    for (auto &d : DIAG_DIRS)
    {
        int r = dr + d[0], c = dc + d[1];
        while (in_bounds(r, c))
        {
            int p = at(r, c);
            if (p != EMPTY) { if (p == W_BISHOP || p == B_BISHOP || p == W_QUEEN || p == B_QUEEN) tally(p); break; }
            r += d[0]; c += d[1];
        }
    }
    for (auto &d : KNIGHT_DIRS)
    {
        int r = dr + d[0], c = dc + d[1];
        if (!in_bounds(r, c)) continue;
        int p = at(r, c);
        if (p == W_KNIGHT || p == B_KNIGHT) tally(p);
    }
    for (int c_dir : {-1, 1})
    {
        if (in_bounds(dr - 1, dc + c_dir)) { int p = at(dr - 1, dc + c_dir); if (p == W_PAWN) tally(p); }
        if (in_bounds(dr + 1, dc + c_dir)) { int p = at(dr + 1, dc + c_dir); if (p == B_PAWN) tally(p); }
    }
    for (int dr2 = -1; dr2 <= 1; ++dr2)
        for (int dc2 = -1; dc2 <= 1; ++dc2)
        {
            if (dr2 == 0 && dc2 == 0) continue;
            int r = dr + dr2, c = dc + dc2;
            if (!in_bounds(r, c)) continue;
            int p = at(r, c);
            if (p == W_KING || p == B_KING) tally(p);
        }

    if (enemies > allies) return -std::abs(PIECE_VALUES[piece_captured]);
    return std::abs(PIECE_VALUES[piece_captured]);
}

int score_move_for_ordering(uint32_t m, const BoardState &st, int ply, uint32_t tt_move)
{
    int from = move_from(m), to = move_to(m);
    int piece = move_piece(m), promo = move_promo(m);
    int target = st.squares[to];

    if (tt_move && m == tt_move) return 2'000'000;
    if (target != EMPTY)
    {
        int see_score = static_exchange_evaluation(st, sq_row(from), sq_col(from), sq_row(to), sq_col(to));
        if (see_score < 0) return 1000 + see_score;
        return 1'000'000 + (10 * std::abs(PIECE_VALUES[target]) - std::abs(PIECE_VALUES[piece])) + see_score;
    }
    if (promo) return 950'000;
    int clamped = std::min(ply, 63);
    if (m == KILLER_MOVES[clamped][0]) return 900'000;
    if (m == KILLER_MOVES[clamped][1]) return 800'000;
    int r = sq_row(to), c = sq_col(to);
    return std::min(HISTORY_TABLE[piece][r][c], 700'000);
}

// ──────────────────────────────────────────────────────────────────────────────
// Quiescence and Minimax (unchanged logic from engine.cpp)
// ──────────────────────────────────────────────────────────────────────────────

using Clock = std::chrono::steady_clock;

int quiescence(BoardState &st, int alpha, int beta, bool maximizing,
               const Clock::time_point &start_t, double time_limit)
{
    if ((STATS.nodes & 255) == 0)
    {
        double elapsed = std::chrono::duration<double>(Clock::now() - start_t).count();
        if (elapsed > time_limit) throw std::runtime_error("timeout");
    }
    STATS.nodes++;

    int stand_pat = evaluate(st);
    if (maximizing)
    {
        if (stand_pat >= beta) return beta;
        if (stand_pat > alpha) alpha = stand_pat;
    }
    else
    {
        if (stand_pat <= alpha) return alpha;
        if (stand_pat < beta)  beta = stand_pat;
    }

    std::vector<uint32_t> all_moves;
    generate_legal_moves(st, maximizing, all_moves);
    std::vector<uint32_t> safe_captures;
    for (uint32_t m : all_moves)
    {
        int to = move_to(m), promo = move_promo(m);
        if (st.squares[to] == EMPTY && promo == 0) continue;
        if (promo != 0)
        {
            safe_captures.push_back(m);
        }
        else
        {
            int from = move_from(m);
            if (static_exchange_evaluation(st, sq_row(from), sq_col(from), sq_row(to), sq_col(to)) >= 0)
                safe_captures.push_back(m);
        }
    }

    std::sort(safe_captures.begin(), safe_captures.end(),
              [&](uint32_t a, uint32_t b)
              { return score_move_for_ordering(a, st, 0, 0) > score_move_for_ordering(b, st, 0, 0); });

    for (uint32_t m : safe_captures)
    {
        UndoInfo ui;
        make_move(st, m, ui);
        int val = quiescence(st, alpha, beta, !maximizing, start_t, time_limit);
        unmake_move(st, ui);
        if (maximizing)
        {
            if (val > alpha) alpha = val;
            if (alpha >= beta) return beta;
        }
        else
        {
            if (val < beta)  beta = val;
            if (beta <= alpha) return alpha;
        }
    }
    return maximizing ? alpha : beta;
}

int minimax(BoardState &st, int depth, int alpha, int beta, bool maximizing, int ply,
            const Clock::time_point &start_t, double time_limit, bool null_move_allowed)
{
    uint64_t h = st.hash;
    if (GAME_HISTORY.count(h) && GAME_HISTORY[h] >= 2) return 0;

    int orig_alpha = alpha;
    uint32_t tt_best_move = 0;

    TTEntry &entry = TT[h % TT_SIZE];
    if (entry.hash == h && entry.depth >= depth)
    {
        int adj_v = retrieve_mate_score(entry.score, ply);
        tt_best_move = entry.best_move;
        if (entry.flag == TT_EXACT) return adj_v;
        else if (entry.flag == TT_LOWER) alpha = std::max(alpha, adj_v);
        else if (entry.flag == TT_UPPER) beta  = std::min(beta,  adj_v);
        if (alpha >= beta) return adj_v;
    }

    if (depth == 0)
        return quiescence(st, alpha, beta, maximizing, start_t, time_limit);

    if ((STATS.nodes & 255) == 0)
    {
        double elapsed = std::chrono::duration<double>(Clock::now() - start_t).count();
        if (elapsed > time_limit) throw std::runtime_error("timeout");
    }
    STATS.nodes++;

    // Null move pruning — lightweight: only hash + side-to-move change,
    // no BoardState copy (avoids copying the 1 KB dual accumulator).
    if (null_move_allowed && depth >= NMP_MIN_DEPTH && nmp_is_safe(st, maximizing, alpha, beta))
    {
        int R = nmp_reduction(depth);
        int null_depth = std::max(0, depth - R - 1);
        // Save only what changes
        uint64_t saved_hash = st.hash;
        bool     saved_wtm  = st.white_to_move;
        hash_side(st);
        st.white_to_move = !st.white_to_move;
        int null_score = minimax(st, null_depth, alpha, beta, !maximizing, ply + 1, start_t, time_limit, false);
        // Restore only what changed
        st.hash          = saved_hash;
        st.white_to_move = saved_wtm;
        if ((maximizing && null_score >= beta) || (!maximizing && null_score <= alpha))
        {
            STATS.nmp_cutoffs++;
            int cutoff_val = maximizing ? beta : alpha;
            entry.hash = h; entry.depth = depth;
            entry.score = store_mate_score(cutoff_val, ply);
            entry.flag = maximizing ? TT_LOWER : TT_UPPER;
            entry.best_move = 0;
            return cutoff_val;
        }
    }

    std::vector<uint32_t> moves;
    generate_legal_moves(st, maximizing, moves);
    if (moves.empty())
    {
        int king_piece = maximizing ? W_KING : B_KING;
        int kr = -1, kc = -1;
        for (int sq = 0; sq < 36; ++sq)
            if (st.squares[sq] == king_piece) { kr = sq_row(sq); kc = sq_col(sq); break; }
        if (kr != -1 && is_attacked(st, kr, kc, !maximizing))
            return maximizing ? -(MATE_VALUE - ply) : (MATE_VALUE - ply);
        return 0;
    }

    std::sort(moves.begin(), moves.end(),
              [&](uint32_t a, uint32_t b)
              { return score_move_for_ordering(a, st, ply, tt_best_move) > score_move_for_ordering(b, st, ply, tt_best_move); });

    int best_v = maximizing ? -1000000000 : 1000000000;
    uint32_t best_move = moves[0];
    bool in_check_now = is_in_check(st, maximizing);

    for (size_t i = 0; i < moves.size(); ++i)
    {
        uint32_t m = moves[i];
        UndoInfo ui;
        make_move(st, m, ui);
        uint64_t child_hash = st.hash;
        int from = move_from(m), to = move_to(m);
        int piece = move_piece(m), promo = move_promo(m);
        int captured = ui.captured_piece;
        int dr_row = sq_row(to);
        int extension = ((piece == W_PAWN && dr_row == 4) || (piece == B_PAWN && dr_row == 1)) ? 1 : 0;

        bool is_capture  = (captured != EMPTY);
        bool is_promo    = (promo != 0);
        int ply_idx      = std::min(ply, 63);
        bool is_killer   = (m == KILLER_MOVES[ply_idx][0] || m == KILLER_MOVES[ply_idx][1]);

        bool use_lmr = (i >= (size_t)LMR_MIN_MOVE_INDEX && depth >= LMR_MIN_DEPTH &&
                        !is_capture && !is_promo && !in_check_now && !is_killer && extension == 0);

        int val;
        if (use_lmr)
        {
            // LMR reduction: capped at min(depth/3, 2) for 6x6.
            // The standard log*log/2 formula is calibrated for 8x8 and over-reduces
            // in a small-board tactical environment. Depth/3 with a hard cap of 2
            // keeps reductions modest so dense tactical sequences are not pruned away.
            int R = std::min({std::max(1, int(std::log(depth) * std::log(int(i) + 1) / 2.0)),
                              depth / 3,
                              2});
            STATS.lmr_reductions++;
            int lmr_alpha = maximizing ? alpha : beta - 1;
            int lmr_beta  = maximizing ? alpha + 1 : beta;
            GAME_HISTORY[child_hash]++;
            val = minimax(st, depth - 1 - R + extension, lmr_alpha, lmr_beta, !maximizing, ply + 1, start_t, time_limit, true);
            if ((maximizing && val > alpha) || (!maximizing && val < beta))
            {
                STATS.lmr_researches++;
                val = minimax(st, depth - 1 + extension, alpha, beta, !maximizing, ply + 1, start_t, time_limit, true);
            }
            GAME_HISTORY[child_hash]--;
        }
        else
        {
            GAME_HISTORY[child_hash]++;
            val = minimax(st, depth - 1 + extension, alpha, beta, !maximizing, ply + 1, start_t, time_limit, true);
            GAME_HISTORY[child_hash]--;
        }

        unmake_move(st, ui);

        if (maximizing)
        {
            if (val > best_v) { best_v = val; best_move = m; }
            if (val > alpha)  alpha = val;
        }
        else
        {
            if (val < best_v) { best_v = val; best_move = m; }
            if (val < beta)   beta = val;
        }

        if (beta <= alpha)
        {
            if (!is_capture)
            {
                int clamped = ply_idx;
                if (m != KILLER_MOVES[clamped][0])
                {
                    KILLER_MOVES[clamped][1] = KILLER_MOVES[clamped][0];
                    KILLER_MOVES[clamped][0] = m;
                }
                int r = sq_row(to), c = sq_col(to);
                HISTORY_TABLE[piece][r][c] += depth * depth;
            }
            STATS.cutoffs++;
            break;
        }
    }

    int flag = (best_v <= orig_alpha) ? TT_UPPER : (best_v >= beta) ? TT_LOWER : TT_EXACT;
    // Depth-preferred replacement: only overwrite if the new search is deeper
    // (or the slot belongs to a different position). This prevents a shallow
    // sweep from evicting an expensive deep result that shares the same index.
    if (entry.hash != h || entry.depth <= depth)
    {
        entry.hash      = h;
        entry.depth     = depth;
        entry.score     = store_mate_score(best_v, ply);
        entry.flag      = flag;
        entry.best_move = best_move;
    }
    return best_v;
}

// ──────────────────────────────────────────────────────────────────────────────
// Root search and C-FFI wrapper
// ──────────────────────────────────────────────────────────────────────────────

std::string format_move_str(uint32_t m)
{
    int from = move_from(m), to = move_to(m);
    int piece = move_piece(m), promo = move_promo(m);
    int sr = sq_row(from), sc = sq_col(from);
    int dr = sq_row(to),   dc = sq_col(to);
    const char files[6] = {'A', 'B', 'C', 'D', 'E', 'F'};
    auto cell = [&](int r, int c) -> std::string
    {
        std::string s; s += files[c]; s += char('1' + r); return s;
    };
    std::string res = std::to_string(piece) + ":" + cell(sr, sc) + "->" + cell(dr, dc);
    if (promo) res += "=" + std::to_string(promo);
    return res;
}

void reset_search_state()
{
    STATS = SearchStats{};
    std::memset(KILLER_MOVES, 0, sizeof(KILLER_MOVES));
    std::memset(HISTORY_TABLE, 0, sizeof(HISTORY_TABLE));
}

// ──────────────────────────────────────────────────────────────────────────────
// C-Interface for Python ctypes  (identical signature to engine.cpp)
// ──────────────────────────────────────────────────────────────────────────────
extern "C"
{
    // Clear per-game repetition history. Must be called at the start of each
    // new game when the same .dll/.so stays loaded across multiple games.
    void reset_game_history()
    {
        GAME_HISTORY.clear();
    }

    // Added 'time_limit' and 'use_noise' parameters
    const char *search_best_move(int *flat_board, bool playing_white, int current_ply, double time_limit, bool use_noise)
    {
        static char output_move[32];

        BoardState state;
        init_board_from_array(state, flat_board, playing_white);

        GAME_HISTORY[state.hash]++;

        double TIME_LIMIT = time_limit; // Now controlled entirely by Python
        reset_search_state();

        std::vector<uint32_t> legal;
        generate_legal_moves(state, playing_white, legal);
        // ── OPENING DIVERSITY (only when use_noise is enabled) ──
        if (use_noise && current_ply <= 3 && !legal.empty())
        {
            std::random_device rd;
            std::mt19937 gen(rd());
            std::uniform_int_distribution<> dist(0, (int)legal.size() - 1);
            
            std::string mv = format_move_str(legal[dist(gen)]);
            GAME_HISTORY[state.hash]--; // Clean up root increment
            std::strcpy(output_move, mv.c_str());
            return output_move;
        }
        if (legal.empty())
        {
            // Decrement before returning (prevent repetition counter leak)
            GAME_HISTORY[state.hash]--;
            std::strcpy(output_move, "NONE");
            return output_move;
        }
        if (legal.size() == 1)
        {
            std::string mv = format_move_str(legal[0]);
            // Decrement before returning
            GAME_HISTORY[state.hash]--;
            std::strcpy(output_move, mv.c_str());
            return output_move;
        }

        uint32_t best_move_so_far = legal[0];
        int best_val_so_far = 0;
        int completed_depth = 0;

        auto start_t = Clock::now();

        for (int d = 1; d < 64; ++d)
        {
            try
            {
                std::sort(legal.begin(), legal.end(),
                          [&](uint32_t a, uint32_t b)
                          { return score_move_for_ordering(a, state, 0, 0) > score_move_for_ordering(b, state, 0, 0); });

                uint32_t local_best_move = 0;
                int local_best_val = playing_white ? -1000000000 : 1000000000;
                int loop_alpha = -1000000000;
                int loop_beta  =  1000000000;

                for (uint32_t m : legal)
                {
                    double elapsed = std::chrono::duration<double>(Clock::now() - start_t).count();
                    if (elapsed > TIME_LIMIT * 0.90) throw std::runtime_error("timeout");

                    UndoInfo ui;
                    make_move(state, m, ui);
                    GAME_HISTORY[state.hash]++;
                    int val = minimax(state, d - 1, loop_alpha, loop_beta,
                                      !playing_white, 1, start_t, TIME_LIMIT * 0.90, true);
                    GAME_HISTORY[state.hash]--;
                    unmake_move(state, ui);

                    if (playing_white)
                    {
                        if (val > local_best_val) { local_best_val = val; local_best_move = m; }
                        if (val > loop_alpha) loop_alpha = val;
                    }
                    else
                    {
                        if (val < local_best_val) { local_best_val = val; local_best_move = m; }
                        if (val < loop_beta) loop_beta = val;
                    }
                }

                if (local_best_move != 0)
                {
                    best_move_so_far = local_best_move;
                    best_val_so_far  = local_best_val;
                    completed_depth  = d;
                }

                auto it = std::find(legal.begin(), legal.end(), best_move_so_far);
                if (it != legal.end()) { legal.erase(it); legal.insert(legal.begin(), best_move_so_far); }

                if (std::abs(best_val_so_far) > 90000) break;
            }
            catch (...) { break; }
        }

        std::string mv = format_move_str(best_move_so_far);
        // Decrement root repetition count before returning
        // (prevents GAME_HISTORY from bloating across successive search calls)
        GAME_HISTORY[state.hash]--;
        std::strcpy(output_move, mv.c_str());
        return output_move;
    }
}
